"""
STARTWISE AI — Franchise Database Seeding Script (Stage 8)

Populates 45 demo franchise records across 10 business categories for hybrid AI recommendation.
Dataset Disclaimer: DEMO / SYNTHETIC DATA generated for academic project demonstration.
"""

import asyncio
from sqlalchemy import select
from app.database.session import AsyncSessionLocal, engine, Base
from app.models.models import Franchise, RiskLevel, BusinessCategory
from app.core.logging import get_logger

logger = get_logger(__name__)

# Disclaimer text attached to demo records
DISCLAIMER_TEXT = (
    "DEMO / SYNTHETIC DATA: Financial parameters (investment, ROI) are indicative estimates "
    "for academic demonstration and do not constitute guaranteed returns or official brand offers."
)

SAMPLE_FRANCHISES = [
    # ── 1. FOOD & BEVERAGE (7 brands) ─────────────────────────────────────────
    {
        "franchise_name": "Tea Time",
        "industry": "Food",
        "business_model": "Kiosk / Express Cafe",
        "minimum_investment": 400000.0,
        "maximum_investment": 600000.0,
        "roi": 45.0,
        "risk_level": "Low",
        "city": "Hyderabad",
        "state": "Telangana",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Students & Office Goers",
        "website": "https://teatime.in",
        "contact_email": "franchise@teatime.in",
        "description": "India's largest tea chain with over 3,000+ outlets serving authentic tea, coffee, and quick bites.",
        "logo_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Low initial capital requirement", "High ROI & quick 6-9 month payback", "Turnkey staff training included"],
        "disadvantages": ["High footfall location dependent", "Intense local competition"],
        "is_active": True,
    },
    {
        "franchise_name": "Amul Ice Cream Parlour",
        "industry": "Food",
        "business_model": "Retail Parlour",
        "minimum_investment": 300000.0,
        "maximum_investment": 500000.0,
        "roi": 40.0,
        "risk_level": "Low",
        "city": "Anand",
        "state": "Gujarat",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Families & Children",
        "website": "https://amul.com",
        "contact_email": "retail@amul.coop",
        "description": "Exclusive Amul ice cream and dairy parlour model with zero royalty or profit sharing fees.",
        "logo_url": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Zero royalty or profit sharing", "Massive household brand pull", "Very low investment entry"],
        "disadvantages": ["Cold chain power backup required", "Fixed trade margin structure"],
        "is_active": True,
    },
    {
        "franchise_name": "Domino's Pizza",
        "industry": "Food",
        "business_model": "QSR & Delivery",
        "minimum_investment": 5000000.0,
        "maximum_investment": 10000000.0,
        "roi": 35.0,
        "risk_level": "High",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "country": "India",
        "experience_required": 5,
        "market_demand": 9,
        "target_customer": "Families & Youth",
        "website": "https://www.dominos.co.in",
        "contact_email": "dominos.franchise@jublfood.com",
        "description": "Global quick-service pizza leader powered by Jubilant FoodWorks with 30-minute delivery ecosystem.",
        "logo_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Top-tier global brand equity", "High ticket size and volume", "Sophisticated POS & app ordering"],
        "disadvantages": ["Very high capital requirement", "Strict multi-unit franchisee qualification"],
        "is_active": True,
    },
    {
        "franchise_name": "Chai Point",
        "industry": "Food",
        "business_model": "Smart Retail Cafe",
        "minimum_investment": 1200000.0,
        "maximum_investment": 2000000.0,
        "roi": 30.0,
        "risk_level": "Medium",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 2,
        "market_demand": 8,
        "target_customer": "Corporate Tech Workers",
        "website": "https://chaipoint.com",
        "contact_email": "franchise@chaipoint.com",
        "description": "Omnichannel tea brand integrating IoT box dispensers and modern retail cafes in tech parks.",
        "logo_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Strong corporate presence", "Proprietary SHARK tech platform", "High repeat customer rate"],
        "disadvantages": ["Higher rent in tech parks", "Requires strict quality compliance"],
        "is_active": True,
    },
    {
        "franchise_name": "Keventers",
        "industry": "Food",
        "business_model": "Milkshake Kiosk",
        "minimum_investment": 2000000.0,
        "maximum_investment": 3000000.0,
        "roi": 32.0,
        "risk_level": "Medium",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "experience_required": 1,
        "market_demand": 7,
        "target_customer": "Gen Z & Youth",
        "website": "https://keventers.com",
        "contact_email": "franchise@keventers.com",
        "description": "Iconic vintage Indian milkshake brand serving dessert shakes in collectible glass bottles.",
        "logo_url": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High gross margin on dairy", "Recognizable vintage packaging", "Mall kiosk format fits small footprint"],
        "disadvantages": ["Seasonal demand fluctuation", "Dairy price volatility"],
        "is_active": True,
    },
    {
        "franchise_name": "RollsKing",
        "industry": "Food",
        "business_model": "Kathi Roll Outlet",
        "minimum_investment": 800000.0,
        "maximum_investment": 1400000.0,
        "roi": 38.0,
        "risk_level": "Low",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Students & Fast Casual Diners",
        "website": "https://rollsking.in",
        "contact_email": "franchise@rollsking.in",
        "description": "Authentic Mughlai kathi roll & wrap chain offering fast takeaway and cloud kitchen formats.",
        "logo_url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Quick preparation time", "Low kitchen equipment cost", "High Swiggy/Zomato volume"],
        "disadvantages": ["Fresh ingredient shelf life", "Local street vendor competition"],
        "is_active": True,
    },
    {
        "franchise_name": "Belgian Waffle Co.",
        "industry": "Food",
        "business_model": "Dessert Kiosk",
        "minimum_investment": 1500000.0,
        "maximum_investment": 2500000.0,
        "roi": 36.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Youth & Families",
        "website": "https://thebelgianwaffle.co",
        "contact_email": "franchise@thebelgianwaffle.co",
        "description": "Pioneer of waffle-wich concept in India with 400+ stores serving freshly baked waffles.",
        "logo_url": "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Unique waffle-wich product format", "High impulse purchase appeal", "Compact 150 sq ft footprint"],
        "disadvantages": ["Requires high footfall mall/high street", "Impulse product nature"],
        "is_active": True,
    },

    # ── 2. RETAIL & LOGISTICS (6 brands) ──────────────────────────────────────
    {
        "franchise_name": "DTDC Express",
        "industry": "Retail",
        "business_model": "Courier & Logistics Hub",
        "minimum_investment": 150000.0,
        "maximum_investment": 300000.0,
        "roi": 35.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "SMEs & E-commerce Sellers",
        "website": "https://www.dtdc.in",
        "contact_email": "channel@dtdc.com",
        "description": "Leading courier and parcel express delivery logistics provider serving 12,000+ pin codes.",
        "logo_url": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Minimal infrastructure risk", "Nationwide trusted logistics network", "Steady daily B2B orders"],
        "disadvantages": ["Regulated corporate rate card", "Daily manual dispatch tracking"],
        "is_active": True,
    },
    {
        "franchise_name": "FirstCry",
        "industry": "Retail",
        "business_model": "Kids Superstore",
        "minimum_investment": 2000000.0,
        "maximum_investment": 3500000.0,
        "roi": 28.0,
        "risk_level": "Medium",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 2,
        "market_demand": 8,
        "target_customer": "Parents & Infants",
        "website": "https://www.firstcry.com",
        "contact_email": "retail@firstcry.com",
        "description": "Asia's largest omnichannel store for baby gear, clothing, toys, and maternity essentials.",
        "logo_url": "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Category leadership in baby retail", "Omnichannel app inventory integration", "High customer lifetime value"],
        "disadvantages": ["Requires large 1,000+ sq ft space", "Working capital in inventory"],
        "is_active": True,
    },
    {
        "franchise_name": "InXpress Logistics",
        "industry": "Logistics",
        "business_model": "Freight Reseller B2B",
        "minimum_investment": 600000.0,
        "maximum_investment": 1000000.0,
        "roi": 42.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Exporters & Manufacturers",
        "website": "https://inxpress.com",
        "contact_email": "franchise@inxpress.com",
        "description": "Global freight reseller consultant partnering with DHL, FedEx, and Aramex for SME shipping.",
        "logo_url": "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=200&q=80",
        "advantages": ["No warehouse or vehicles needed", "High margin recurring B2B contracts", "Work from office/home"],
        "disadvantages": ["Requires consultative sales skill", "B2B client acquisition effort"],
        "is_active": True,
    },
    {
        "franchise_name": "Bata Shoe Store",
        "industry": "Retail",
        "business_model": "Footwear Exclusive Store",
        "minimum_investment": 3000000.0,
        "maximum_investment": 5000000.0,
        "roi": 26.0,
        "risk_level": "Medium",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 3,
        "market_demand": 8,
        "target_customer": "Families & School Students",
        "website": "https://bata.in",
        "contact_email": "franchise@bata.com",
        "description": "Heritage footwear retail chain offering school shoes, formal wear, and casual sneakers.",
        "logo_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Unrivaled 100-year brand legacy", "High back-to-school seasonal footfall", "Centralized inventory replenishment"],
        "disadvantages": ["High commercial street rental cost", "Stock management per size SKU"],
        "is_active": True,
    },
    {
        "franchise_name": "Miniso",
        "industry": "Retail",
        "business_model": "Lifestyle & Gift Store",
        "minimum_investment": 5000000.0,
        "maximum_investment": 8000000.0,
        "roi": 30.0,
        "risk_level": "Medium",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 3,
        "market_demand": 9,
        "target_customer": "Teenagers & Young Adults",
        "website": "https://miniso.com",
        "contact_email": "franchise@miniso.com",
        "description": "Global designer lifestyle product store specializing in cute stationary, plushies, and cosmetics.",
        "logo_url": "https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High impulse buy rate", "Regular IP collaborations (Disney, Marvel)", "High store footfall density"],
        "disadvantages": ["High capital expenditure", "Fast product rotation cycles"],
        "is_active": True,
    },
    {
        "franchise_name": "Delhivery Express",
        "industry": "Logistics",
        "business_model": "Last-mile Logistics Hub",
        "minimum_investment": 200000.0,
        "maximum_investment": 500000.0,
        "roi": 38.0,
        "risk_level": "Low",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "E-Commerce Merchants",
        "website": "https://delhivery.com",
        "contact_email": "partner@delhivery.com",
        "description": "India's largest logistics tech platform for last-mile pickup and delivery center franchise.",
        "logo_url": "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&w=200&q=80",
        "advantages": ["E-commerce surge volume", "Minimal office space required", "Technology-driven routing"],
        "disadvantages": ["Dependency on delivery manpower", "Per-parcel thin margins"],
        "is_active": True,
    },

    # ── 3. HEALTHCARE & PHARMA (5 brands) ──────────────────────────────────────
    {
        "franchise_name": "Apollo Pharmacy",
        "industry": "Healthcare",
        "business_model": "Retail Chemist & Wellness",
        "minimum_investment": 1000000.0,
        "maximum_investment": 1500000.0,
        "roi": 30.0,
        "risk_level": "Low",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "experience_required": 1,
        "market_demand": 10,
        "target_customer": "Patients & Elderly",
        "website": "https://www.apollopharmacy.in",
        "contact_email": "franchise@apollopharmacy.org",
        "description": "Asia's largest pharmacy retail network with 5,000+ outlets delivering genuine medicines 24/7.",
        "logo_url": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Recession-proof essential healthcare industry", "100% genuine medicine supply chain", "Apollo 24|7 app linkage"],
        "disadvantages": ["Registered Pharmacist mandatory", "DPCO price capped drug margins"],
        "is_active": True,
    },
    {
        "franchise_name": "Lenskart",
        "industry": "Healthcare",
        "business_model": "Optical & Eye Testing Store",
        "minimum_investment": 3000000.0,
        "maximum_investment": 4500000.0,
        "roi": 32.0,
        "risk_level": "Medium",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 2,
        "market_demand": 9,
        "target_customer": "Eyewear Buyers",
        "website": "https://www.lenskart.com",
        "contact_email": "franchise@lenskart.com",
        "description": "Omnichannel eyewear unicorn store with free 3D eye testing and stylish frame collections.",
        "logo_url": "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High gross profit margin on lenses", "Free automated eye test machine", "Unicorn marketing campaigns"],
        "disadvantages": ["Optometrist salary cost", "High interior fit-out standard"],
        "is_active": True,
    },
    {
        "franchise_name": "Dr. Lal PathLabs",
        "industry": "Healthcare",
        "business_model": "Diagnostic Collection Center",
        "minimum_investment": 300000.0,
        "maximum_investment": 600000.0,
        "roi": 40.0,
        "risk_level": "Low",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Patients & Clinics",
        "website": "https://lalpathlabs.com",
        "contact_email": "franchise@lalpathlabs.com",
        "description": "Leading Indian diagnostic chain collection center for blood tests, pathology, and health checkups.",
        "logo_url": "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Very low initial capital", "No complex lab testing on-site (sample pickup)", "High brand trust"],
        "disadvantages": ["Phlebotomist hiring required", "Doctor referral networking effort"],
        "is_active": True,
    },
    {
        "franchise_name": "MedPlus Pharmacy",
        "industry": "Healthcare",
        "business_model": "Discount Pharmacy",
        "minimum_investment": 800000.0,
        "maximum_investment": 1400000.0,
        "roi": 28.0,
        "risk_level": "Low",
        "city": "Hyderabad",
        "state": "Telangana",
        "country": "India",
        "experience_required": 1,
        "market_demand": 9,
        "target_customer": "Chronic Disease Patients",
        "website": "https://medplusindia.com",
        "contact_email": "franchise@medplusindia.com",
        "description": "Second largest pharmacy chain offering genuine branded medicines and diagnostic services.",
        "logo_url": "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Strong customer loyalty rewards", "High volume chronic prescription refill", "Centralized warehouse supply"],
        "disadvantages": ["Discount competitive pressure", "Requires licensed pharmacist"],
        "is_active": True,
    },
    {
        "franchise_name": "Metropolis Healthcare",
        "industry": "Healthcare",
        "business_model": "Pathology Collection Center",
        "minimum_investment": 400000.0,
        "maximum_investment": 700000.0,
        "roi": 38.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Diagnostic Patients",
        "website": "https://metropolisindia.com",
        "contact_email": "partner@metropolisindia.com",
        "description": "NABL accredited pathology lab collection center offering 4,000+ specialized medical tests.",
        "logo_url": "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=200&q=80",
        "advantages": ["NABL quality accreditation pull", "High margin specialized genomic tests", "Home sample pickup software"],
        "disadvantages": ["Requires local hospital/doctor ties", "Cold sample logistics timing"],
        "is_active": True,
    },

    # ── 4. EDUCATION & TRAINING (5 brands) ────────────────────────────────────
    {
        "franchise_name": "Kidzee Preschool",
        "industry": "Education",
        "business_model": "Early Childhood Education",
        "minimum_investment": 1200000.0,
        "maximum_investment": 2000000.0,
        "roi": 35.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Toddlers & Young Parents",
        "website": "https://kidzee.com",
        "contact_email": "franchise@kidzee.com",
        "description": "Asia's largest preschool network with 2,000+ centers powered by Zee Learn iLLUME curriculum.",
        "logo_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High recurring annual fee structure", "Proprietary iLLUME pedagogy", "High parent community trust"],
        "disadvantages": ["Requires 2,000+ sq ft residential/commercial plot", "Safety audit compliance"],
        "is_active": True,
    },
    {
        "franchise_name": "EuroKids International",
        "industry": "Education",
        "business_model": "Premium Preschool",
        "minimum_investment": 1500000.0,
        "maximum_investment": 2500000.0,
        "roi": 32.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Premium Working Parents",
        "website": "https://eurokidsindia.com",
        "contact_email": "franchise@eurokidsindia.com",
        "description": "Award-winning pre-school chain focusing on EUNOIA mindful learning curriculum and child safety.",
        "logo_url": "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Higher fee premium tier", "Comprehensive teacher training", "CCTV & safety protocols"],
        "disadvantages": ["Higher setup fitout expenditure", "Seasonal admission cycle"],
        "is_active": True,
    },
    {
        "franchise_name": "CL Educate (Career Launcher)",
        "industry": "Education",
        "business_model": "Test Prep Coaching Center",
        "minimum_investment": 800000.0,
        "maximum_investment": 1500000.0,
        "roi": 40.0,
        "risk_level": "Medium",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "experience_required": 2,
        "market_demand": 8,
        "target_customer": "CAT, CLAT & IPMAT Aspirants",
        "website": "https://careerlauncher.com",
        "contact_email": "partner@careerlauncher.com",
        "description": "Premier test preparation institute for CAT, CLAT, IPMAT, GRE, and study abroad entrance exams.",
        "logo_url": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High margin tuition fees", "Online + offline hybrid portal", "Established national top ranker track record"],
        "disadvantages": ["Faculty recruitment & retention challenge", "Local coaching institute competition"],
        "is_active": True,
    },
    {
        "franchise_name": "T.I.M.E. Institute",
        "industry": "Education",
        "business_model": "Competitive Exam Center",
        "minimum_investment": 1000000.0,
        "maximum_investment": 1800000.0,
        "roi": 38.0,
        "risk_level": "Medium",
        "city": "Secunderabad",
        "state": "Telangana",
        "country": "India",
        "experience_required": 2,
        "market_demand": 9,
        "target_customer": "College Graduates & Engineers",
        "website": "https://time4education.com",
        "contact_email": "franchise@time4education.com",
        "description": "India's leading test prep institute for CAT, GATE, Bank PO, SSC, and campus recruitment training.",
        "logo_url": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Massive student enrollment volume", "Comprehensive printed material supply", "Mock test series portal"],
        "disadvantages": ["Faculty dependence", "Requires central city location"],
        "is_active": True,
    },
    {
        "franchise_name": "ALOHA India",
        "industry": "Education",
        "business_model": "Abacus & Mental Math Center",
        "minimum_investment": 200000.0,
        "maximum_investment": 400000.0,
        "roi": 50.0,
        "risk_level": "Low",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "School Children (Age 5-13)",
        "website": "https://alohaindia.com",
        "contact_email": "franchise@alohaindia.com",
        "description": "International mental arithmetic, speed math, and abacus brain development center for kids.",
        "logo_url": "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Very low initial capital", "Weekend batch operational model", "High profit margin"],
        "disadvantages": ["Niche age group target", "Parent retention effort"],
        "is_active": True,
    },

    # ── 5. BEAUTY & WELLNESS (5 brands) ───────────────────────────────────────
    {
        "franchise_name": "Naturals Beauty Salon",
        "industry": "Services",
        "business_model": "Unisex Beauty Salon",
        "minimum_investment": 3500000.0,
        "maximum_investment": 5500000.0,
        "roi": 30.0,
        "risk_level": "Medium",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Women & Men",
        "website": "https://naturals.in",
        "contact_email": "franchise@naturals.in",
        "description": "India's No.1 unisex hair and beauty salon chain operating 700+ stores across South India.",
        "logo_url": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High customer repeat rate", "Tier-1 celebrity brand endorsements", "L'Oreal product partner tieup"],
        "disadvantages": ["Stylist attrition & poaching risk", "High interior fitout cost"],
        "is_active": True,
    },
    {
        "franchise_name": "Lakmé Salon",
        "industry": "Services",
        "business_model": "Premium Bridal & Hair Salon",
        "minimum_investment": 5000000.0,
        "maximum_investment": 8000000.0,
        "roi": 28.0,
        "risk_level": "Medium",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 2,
        "market_demand": 9,
        "target_customer": "Bridal & High Net Worth Women",
        "website": "https://lakmesalon.in",
        "contact_email": "franchise@lakmesalon.in",
        "description": "Unilever-backed flagship salon brand pioneering runway beauty trends and bridal makeovers.",
        "logo_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Premium bridal package pricing", "Unilever corporate governance", "Lakme Fashion Week backing"],
        "disadvantages": ["Significant initial investment", "Requires prime commercial location"],
        "is_active": True,
    },
    {
        "franchise_name": "Jawad Habib HairXpreso",
        "industry": "Services",
        "business_model": "Express Haircut Kiosk",
        "minimum_investment": 1000000.0,
        "maximum_investment": 1800000.0,
        "roi": 38.0,
        "risk_level": "Low",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Budget Conscious Youth",
        "website": "https://jawedhabib.co.in",
        "contact_email": "franchise@jh.co.in",
        "description": "Affordable express hair grooming franchise founded by celebrity hair stylist Jawed Habib.",
        "logo_url": "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Affordable price point volume model", "Jawed Habib celebrity brand recognition", "Quick 15-minute haircut throughput"],
        "disadvantages": ["Lower ticket size per customer", "Local barber shop price pressure"],
        "is_active": True,
    },
    {
        "franchise_name": "Shahnaz Husain Herbal",
        "industry": "Services",
        "business_model": "Ayurvedic Beauty Clinic",
        "minimum_investment": 1500000.0,
        "maximum_investment": 2500000.0,
        "roi": 32.0,
        "risk_level": "Low",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "experience_required": 1,
        "market_demand": 7,
        "target_customer": "Ayurvedic Skincare Enthusiasts",
        "website": "https://shahnaz.in",
        "contact_email": "franchise@shahnaz.in",
        "description": "Pioneer of organic herbal care and Ayurvedic facial treatment salons worldwide.",
        "logo_url": "https://images.unsplash.com/photo-1512290900673-7002fffe9446?auto=format&fit=crop&w=200&q=80",
        "advantages": ["100% natural organic product line", "Strong export & domestic trust", "High product retail margin"],
        "disadvantages": ["Niche Ayurvedic target focus", "Competition from modern dermatology clinics"],
        "is_active": True,
    },
    {
        "franchise_name": "VLCC Wellness",
        "industry": "Services",
        "business_model": "Slimming & Beauty Center",
        "minimum_investment": 4000000.0,
        "maximum_investment": 7000000.0,
        "roi": 27.0,
        "risk_level": "Medium",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 2,
        "market_demand": 8,
        "target_customer": "Weight Loss & Clinical Skincare Clients",
        "website": "https://vlccwellness.com",
        "contact_email": "franchise@vlccwellness.com",
        "description": "Scientific weight management, clinical dermatology, and therapeutic wellness centers.",
        "logo_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High ticket slimming package sales", "Medical doctor & nutritionist backed", "Strong corporate brand"],
        "disadvantages": ["High machinery capital expense", "Requires qualified dietitian staff"],
        "is_active": True,
    },

    # ── 6. TECHNOLOGY & SERVICES (5 brands) ──────────────────────────────────
    {
        "franchise_name": "Tally Academy",
        "industry": "Technology",
        "business_model": "GST & Accounting Training Center",
        "minimum_investment": 300000.0,
        "maximum_investment": 600000.0,
        "roi": 45.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 0,
        "market_demand": 9,
        "target_customer": "Commerce Students & Job Seekers",
        "website": "https://tallyeducation.com",
        "contact_email": "partner@tallyeducation.com",
        "description": "Official Tally Prime, GST taxation, and computerized accounting training partner institute.",
        "logo_url": "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Official Tally Prime certification provider", "Huge demand from commerce graduates", "Low computer lab setup cost"],
        "disadvantages": ["Requires updated GST curriculum materials", "Local computer institute price competition"],
        "is_active": True,
    },
    {
        "franchise_name": "Gharpayy Tech",
        "industry": "Technology",
        "business_model": "Co-living Aggregator Operator",
        "minimum_investment": 1500000.0,
        "maximum_investment": 3000000.0,
        "roi": 36.0,
        "risk_level": "Medium",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 1,
        "market_demand": 9,
        "target_customer": "Migrant IT Professionals",
        "website": "https://gharpayy.com",
        "contact_email": "franchise@gharpayy.com",
        "description": "Tech-enabled managed co-living PG and student housing property operations franchise.",
        "logo_url": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High monthly rental cash flow", "Tech app booking engine", "High IT hub demand"],
        "disadvantages": ["Long term master property lease risk", "Property maintenance overhead"],
        "is_active": True,
    },
    {
        "franchise_name": "CSC e-Governance Digital",
        "industry": "Technology",
        "business_model": "Common Service Center Kiosk",
        "minimum_investment": 100000.0,
        "maximum_investment": 250000.0,
        "roi": 55.0,
        "risk_level": "Low",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "experience_required": 0,
        "market_demand": 10,
        "target_customer": "Rural & Semi-Urban Citizens",
        "website": "https://csc.gov.in",
        "contact_email": "support@csc.gov.in",
        "description": "Government of India e-Governance Common Services Center delivering Aadhaar, PAN, and passport services.",
        "logo_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Government authorized service provider", "Lowest investment threshold", "Massive citizen footfall"],
        "disadvantages": ["Fixed government commission rates", "Regulated hardware specifications"],
        "is_active": True,
    },
    {
        "franchise_name": "Hero Electric Dealership",
        "industry": "Automotive",
        "business_model": "EV Scooter Showroom & Service",
        "minimum_investment": 3000000.0,
        "maximum_investment": 6000000.0,
        "roi": 32.0,
        "risk_level": "Medium",
        "city": "Ludhiana",
        "state": "Punjab",
        "country": "India",
        "experience_required": 2,
        "market_demand": 9,
        "target_customer": "Commuters & Delivery Riders",
        "website": "https://heroelectric.in",
        "contact_email": "dealer@heroelectric.in",
        "description": "Pioneer EV two-wheeler dealership and service center tapping India's electric mobility transition.",
        "logo_url": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High EV market growth rate", "Government FAME-II subsidy push", "Scooter sales + lithium battery service revenue"],
        "disadvantages": ["Showroom commercial space requirement", "Working capital locked in scooter inventory"],
        "is_active": True,
    },
    {
        "franchise_name": "Ather Energy Space",
        "industry": "Automotive",
        "business_model": "Premium EV Experience Center",
        "minimum_investment": 6000000.0,
        "maximum_investment": 10000000.0,
        "roi": 28.0,
        "risk_level": "Medium",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 3,
        "market_demand": 9,
        "target_customer": "Tech-savvy Urban Youth",
        "website": "https://atherenergy.com",
        "contact_email": "retail@atherenergy.com",
        "description": "Next-gen premium smart electric scooter experience center and Ather Grid fast-charging hub.",
        "logo_url": "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Apple-like premium retail experience", "Ather Grid fast charging footfall", "OTA software update scooter selling point"],
        "disadvantages": ["High initial capital requirement", "Strict location aesthetic standards"],
        "is_active": True,
    },

    # ── 7. AUTOMOTIVE & SERVICES (4 brands) ───────────────────────────────────
    {
        "franchise_name": "3M Car Care",
        "industry": "Automotive",
        "business_model": "Auto Detailing Studio",
        "minimum_investment": 3500000.0,
        "maximum_investment": 5500000.0,
        "roi": 34.0,
        "risk_level": "Medium",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 2,
        "market_demand": 8,
        "target_customer": "Car Enthusiasts & Luxury Vehicle Owners",
        "website": "https://3mcarcare.in",
        "contact_email": "franchise@3mcarcare.in",
        "description": "World leader in ceramic coating, paint protection film (PPF), and premium car detailing.",
        "logo_url": "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High margin luxury detailing packages", "3M global product chemistry leadership", "High repeat customer retention"],
        "disadvantages": ["Requires 2,500+ sq ft workshop space", "Skilled detailing technician dependency"],
        "is_active": True,
    },
    {
        "franchise_name": "Express Car Wash",
        "industry": "Automotive",
        "business_model": "Automated Car Wash Studio",
        "minimum_investment": 1500000.0,
        "maximum_investment": 2500000.0,
        "roi": 42.0,
        "risk_level": "Low",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Urban Car Owners",
        "website": "https://expresscarwash.in",
        "contact_email": "info@expresscarwash.in",
        "description": "Eco-friendly steam car wash and automated foam cleaning system franchise.",
        "logo_url": "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Water recycling & steam cleaning technology", "Quick 20-minute car turnaround", "High monthly subscription revenue"],
        "disadvantages": ["Commercial water connection requirement", "High pressure pump maintenance"],
        "is_active": True,
    },
    {
        "franchise_name": "CleanDrive Eco Wash",
        "industry": "Services",
        "business_model": "Doorstep Waterless Car Spa",
        "minimum_investment": 300000.0,
        "maximum_investment": 600000.0,
        "roi": 48.0,
        "risk_level": "Low",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Gated Community Residents",
        "website": "https://cleandrive.in",
        "contact_email": "contact@cleandrive.in",
        "description": "App-based doorstep waterless car cleaning subscription service for gated apartments.",
        "logo_url": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Zero workshop rent required", "Predictable monthly subscription revenue", "Eco-friendly marketing appeal"],
        "disadvantages": ["Daily cleaner workforce management", "Apartment association permissions"],
        "is_active": True,
    },
    {
        "franchise_name": "Urban Laundry Co.",
        "industry": "Services",
        "business_model": "Dry Cleaning & Laundromat",
        "minimum_investment": 1200000.0,
        "maximum_investment": 2000000.0,
        "roi": 36.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Bachelor Professionals & Families",
        "website": "https://urbanlaundry.in",
        "contact_email": "franchise@urbanlaundry.in",
        "description": "Italian eco-friendly dry cleaning and express laundromat service store.",
        "logo_url": "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Essential household service demand", "High commercial garment cleaning margins", "App-based pickup delivery"],
        "disadvantages": ["Boiler & washer machinery maintenance", "Steam chemical safety handling"],
        "is_active": True,
    },

    # ── 8. FITNESS & WELLNESS (4 brands) ─────────────────────────────────────
    {
        "franchise_name": "Cult.fit Gym",
        "industry": "Fitness",
        "business_model": "Group Workout & Gym Center",
        "minimum_investment": 6000000.0,
        "maximum_investment": 10000000.0,
        "roi": 30.0,
        "risk_level": "Medium",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 2,
        "market_demand": 9,
        "target_customer": "Urban Fitness Enthusiasts",
        "website": "https://cult.fit",
        "contact_email": "partner@cult.fit",
        "description": "Tech-driven flagship gym network offering HRX, Boxing, Yoga, and Strength group classes.",
        "logo_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Unicorn app member traffic routing", "High cult brand loyalty", "Standardized trainer curriculum"],
        "disadvantages": ["Large 4,000+ sq ft commercial floor plate", "High fitness equipment capital cost"],
        "is_active": True,
    },
    {
        "franchise_name": "Gold's Gym India",
        "industry": "Fitness",
        "business_model": "Premium Health Club",
        "minimum_investment": 8000000.0,
        "maximum_investment": 15000000.0,
        "roi": 25.0,
        "risk_level": "Medium",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "experience_required": 3,
        "market_demand": 8,
        "target_customer": "HNIs & Bodybuilders",
        "website": "https://goldsgym.in",
        "contact_email": "franchise@goldsgym.in",
        "description": "World famous heritage health club brand providing luxury gymming and personal training.",
        "logo_url": "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Global iconic bodybuilding legacy", "High annual membership price point", "Personal trainer revenue share"],
        "disadvantages": ["High commercial real estate rent", "Heavy gym equipment import duties"],
        "is_active": True,
    },
    {
        "franchise_name": "Snap Fitness 24/7",
        "industry": "Fitness",
        "business_model": "24 Hour Neighborhood Gym",
        "minimum_investment": 4000000.0,
        "maximum_investment": 7000000.0,
        "roi": 32.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Shift Workers & Night Owls",
        "website": "https://snapfitness.com",
        "contact_email": "franchise@snapfitness.com",
        "description": "Global 24/7 access gym franchise featuring keycard entry and Matrix strength equipment.",
        "logo_url": "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=200&q=80",
        "advantages": ["24/7 automated keycard access", "Lower staffing costs off-peak", "Compact 2,500 sq ft model"],
        "disadvantages": ["24-hour security & CCTV monitoring", "Continuous HVAC power expense"],
        "is_active": True,
    },
    {
        "franchise_name": "Yoga360 Studio",
        "industry": "Fitness",
        "business_model": "Mindfulness & Pilates Studio",
        "minimum_investment": 800000.0,
        "maximum_investment": 1500000.0,
        "roi": 42.0,
        "risk_level": "Low",
        "city": "Rishikesh",
        "state": "Uttarakhand",
        "country": "India",
        "experience_required": 1,
        "market_demand": 8,
        "target_customer": "Wellness Seekers & Women",
        "website": "https://yoga360.in",
        "contact_email": "contact@yoga360.in",
        "description": "Holistic Hatha yoga, reformer Pilates, and sound bath meditation studio franchise.",
        "logo_url": "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Low machinery & equipment cost", "High monthly subscription margin", "Calm aesthetic community appeal"],
        "disadvantages": ["Master yoga instructor dependency", "Niche wellness audience"],
        "is_active": True,
    },

    # ── 9. SERVICES & REPAIR (4 brands) ───────────────────────────────────────
    {
        "franchise_name": "Mobikwik Repair Hub",
        "industry": "Services",
        "business_model": "Mobile & Laptop Repair Kiosk",
        "minimum_investment": 300000.0,
        "maximum_investment": 600000.0,
        "roi": 48.0,
        "risk_level": "Low",
        "city": "Gurugram",
        "state": "Haryana",
        "country": "India",
        "experience_required": 1,
        "market_demand": 9,
        "target_customer": "Smartphone & Laptop Users",
        "website": "https://mobikwik.com",
        "contact_email": "repair@mobikwik.com",
        "description": "Express 30-minute smartphone glass, battery, and motherboard repair center.",
        "logo_url": "https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High margin spare parts markups", "Fast 30-minute repair throughput", "Small 100 sq ft store format"],
        "disadvantages": ["Skilled hardware technician hiring", "Spare part counterfeit risks"],
        "is_active": True,
    },
    {
        "franchise_name": "Presto Personalised Gifts",
        "industry": "Retail",
        "business_model": "Custom Gift Printing Kiosk",
        "minimum_investment": 500000.0,
        "maximum_investment": 900000.0,
        "roi": 40.0,
        "risk_level": "Low",
        "city": "Kolkata",
        "state": "West Bengal",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Gifters & Corporate Buyers",
        "website": "https://prestogifts.com",
        "contact_email": "franchise@prestogifts.com",
        "description": "Custom laser engraving, 3D crystals, personalized mugs, and corporate award gifts.",
        "logo_url": "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Instant high-margin custom product creation", "Peak Valentine & Diwali festival sales", "Compact mall kiosk model"],
        "disadvantages": ["Laser engraver machinery maintenance", "Inventory of blank gift stock"],
        "is_active": True,
    },
    {
        "franchise_name": "Speedy Lock & Security",
        "industry": "Services",
        "business_model": "Digital Lock & Key Kiosk",
        "minimum_investment": 250000.0,
        "maximum_investment": 500000.0,
        "roi": 50.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 0,
        "market_demand": 8,
        "target_customer": "Homeowners & Car Owners",
        "website": "https://speedylock.in",
        "contact_email": "contact@speedylock.in",
        "description": "Biometric smart lock installation, RFID key cloning, and emergency locksmith service.",
        "logo_url": "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=200&q=80",
        "advantages": ["High margin smart lock sales", "Minimal inventory requirement", "Emergency service callout rates"],
        "disadvantages": ["Technical key cloning equipment operation", "Local hardware shop competition"],
        "is_active": True,
    },
    {
        "franchise_name": "PetCare World Clinic",
        "industry": "Services",
        "business_model": "Pet Grooming & Retail Spa",
        "minimum_investment": 1500000.0,
        "maximum_investment": 2500000.0,
        "roi": 35.0,
        "risk_level": "Low",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "experience_required": 1,
        "market_demand": 9,
        "target_customer": "Pet Parents & Dog Owners",
        "website": "https://petcareworld.in",
        "contact_email": "franchise@petcareworld.in",
        "description": "Comprehensive pet spa, dog grooming salon, vet consultation, and premium pet food store.",
        "logo_url": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=200&q=80",
        "advantages": ["Booming urban pet humanization trend", "High repeat monthly grooming bookings", "High margin imported pet food"],
        "disadvantages": ["Requires trained pet groomers", "Animal behavior handling care"],
        "is_active": True,
    },
]


async def seed_franchises():
    print("\n" + "=" * 60)
    print("  STARTWISE AI — FRANCHISE DATABASE SEEDING (STAGE 8)")
    print(f"  Total records to process: {len(SAMPLE_FRANCHISES)}")
    print("=" * 60)

    # Ensure tables are created
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as db:
        added_count = 0
        updated_count = 0

        for item in SAMPLE_FRANCHISES:
            # Check if franchise name exists
            stmt = select(Franchise).where(Franchise.franchise_name == item["franchise_name"])
            res = await db.execute(stmt)
            existing = res.scalar_one_or_none()

            if existing:
                # Update existing record
                for k, v in item.items():
                    setattr(existing, k, v)
                updated_count += 1
            else:
                # Create new record
                new_f = Franchise(**item)
                db.add(new_f)
                added_count += 1

        await db.commit()
        print(f"\n  [OK] Successfully seeded franchises database:")
        print(f"       • Added new records  : {added_count}")
        print(f"       • Updated existing   : {updated_count}")
        print(f"       • Total in database  : {added_count + updated_count}")
        print("\n" + "=" * 60 + "\n")


if __name__ == "__main__":
    asyncio.run(seed_franchises())
